fix: extract github actions secrets
storming0x/foundry_strategy_mix pull request #27
Opened 2022-08-02 10:29 UTC by githinho

Extract `INFURA_API_KEY` and `ETHERSCAN_API_KEY` to GitHub action secrets.

2022-08-04 18:46 UTC, storming0x commented on README.md
> +Note though that to make this work, you must se your `INFURA_API_KEY` and your `ETHERSCAN_API_KEY` as GitHub secrets.
small typo*

2022-08-04 18:46 UTC, storming0x requested changes
small typo and should be good to merge

2022-08-04 18:53 UTC, storming0x commented on .github/workflows/test.yaml
> +          ETH_RPC_URL: https://mainnet.infura.io/v3/${{ secrets.INFURA_API_KEY }}
I added the SECRETS , but tests CI doesn't work, CI step in trace seems to not find the etherscan key

2022-08-04 19:04 UTC, storming0x requested changes

2022-08-04 19:04 UTC, storming0x commented on .github/workflows/test.yaml
> +          ETH_RPC_URL: https://mainnet.infura.io/v3/${{ secrets.INFURA_API_KEY }}
Added secrets to environment and repo secrets but makefile step doesnt seem to pull them for some reason

> Run make trace
> forge test -vvv --fork-url https://mainnet.infura.io/v3/  --etherscan-api-key 
> error: The argument '--etherscan-api-key <ETHERSCAN_KEY>' requires a value but none was supplied

2022-08-04 19:37 UTC, githinho commented on .github/workflows/test.yaml
> +          ETH_RPC_URL: https://mainnet.infura.io/v3/${{ secrets.INFURA_API_KEY }}
`${{ secrets.INFURA_API_KEY }}` is the syntax just for Github actions(CI).  This PR will apply only as CI changes.
If you run it locally, you should have `.env` file the same as before. I have `.env` file locally and `make trace` works correctly. Let me know if still have the same problem.

The setup for actions secrets should look like this:
![image](https://user-images.githubusercontent.com/7816423/182937182-d24535f8-487b-47ee-ab49-e831cd40f1cb.png)

2022-08-04 20:51 UTC, storming0x commented on .github/workflows/test.yaml
> +          ETH_RPC_URL: https://mainnet.infura.io/v3/${{ secrets.INFURA_API_KEY }}
> The setup for actions secrets should look like this: ![image](https://user-images.githubusercontent.com/7816423/182937182-d24535f8-487b-47ee-ab49-e831cd40f1cb.png)

Understood, i added the secrets to repo as the image shows, still the CI step is not passing, check the fail message below the PR,

i was looking into this example shared: https://gist.github.com/sambacha/89129cdeb59fd6098a5b46ea8b9664e2

Maybe replacing here:

https://github.com/storming0x/foundry_strategy_mix/blob/8342b1f11a04954c573caa76de65fce06c5cf537/.github/workflows/test.yaml#L28

`forge test -vvv --fork-url "$ETH_RPC_URL" --etherscan-api-key "$ETHERSCAN_API_KEY"`

2022-08-05 12:18 UTC, githinho commented on .github/workflows/test.yaml
> +          ETH_RPC_URL: https://mainnet.infura.io/v3/${{ secrets.INFURA_API_KEY }}
I have changed the command for running test, no more `make`. Also, added ETH_RPC_URL secret on my side and it works.
![image](https://user-images.githubusercontent.com/7816423/183075594-aacfa2ac-b685-4931-b012-d5f96e322cbd.png)

2022-08-05 17:31 UTC, storming0x approved these changes
will merge in case for some reason

2022-08-05 17:31 UTC, merged